language: node_js
dist: xenial
services:
  - xvfb
node_js:
  - stable
  - 10
  - 8
matrix:
  fast_finish: true
  include:
    - node_js: stable
      os: osx
    - node_js: 12
      env: ELECTRON_VERSION=5
    - node_js: 10
      env: ELECTRON_VERSION=4
    - node_js: 8
      env: ELECTRON_VERSION=3
    #- node_js: stable
    # env: ELECTRON_VERSION=beta
before_install:
  - if [[ -n $ELECTRON_VERSION ]]; then
      npm install electron@$ELECTRON_VERSION;
    fi
install:
  - npm install --no-progress
  - $(npm bin)/electron --version
script:
  - npm test
notifications:
  email: false
